import hashlib
import hmac
import jwt
from datetime import datetime, timedelta
from typing import Optional, Dict, Any
from fastapi import HTTPException, status
from config.settings import settings

class SecurityManager:
    @staticmethod
        def create_access_token(data: Dict[str, Any]) -> str:
                """Create JWT access token"""
                        to_encode = data.copy()
                                expire = datetime.utcnow() + timedelta(minutes=settings.access_token_expire_minutes)
                                        to_encode.update({"exp": expire})
                                                
                                                        encoded_jwt = jwt.encode(
                                                                    to_encode, 
                                                                                settings.secret_key, 
                                                                                            algorithm=settings.algorithm
                                                                                                    )
                                                                                                            return encoded_jwt
                                                                                                                
                                                                                                                    @staticmethod
                                                                                                                        def verify_token(token: str) -> Dict[str, Any]:
                                                                                                                                """Verify JWT token"""
                                                                                                                                        try:
                                                                                                                                                    payload = jwt.decode(
                                                                                                                                                                    token, 
                                                                                                                                                                                    settings.secret_key, 
                                                                                                                                                                                                    algorithms=[settings.algorithm]
                                                                                                                                                                                                                )
                                                                                                                                                                                                                            return payload
                                                                                                                                                                                                                                    except jwt.PyJWTError:
                                                                                                                                                                                                                                                raise HTTPException(
                                                                                                                                                                                                                                                                status_code=status.HTTP_401_UNAUTHORIZED,
                                                                                                                                                                                                                                                                                detail="Invalid authentication credentials",
                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                    @staticmethod
                                                                                                                                                                                                                                                                                                        def verify_webhook_signature(payload: bytes, signature: str, secret: str) -> bool:
                                                                                                                                                                                                                                                                                                                """Verify webhook signature"""
                                                                                                                                                                                                                                                                                                                        expected_signature = hmac.new(
                                                                                                                                                                                                                                                                                                                                    secret.encode('utf-8'),
                                                                                                                                                                                                                                                                                                                                                payload,
                                                                                                                                                                                                                                                                                                                                                            hashlib.sha256
                                                                                                                                                                                                                                                                                                                                                                    ).hexdigest()
                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                    return hmac.compare_digest(expected_signature, signature)
                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                            @staticmethod
                                                                                                                                                                                                                                                                                                                                                                                                def sanitize_input(text: str) -> str:
                                                                                                                                                                                                                                                                                                                                                                                                        """Sanitize user input to prevent injection attacks"""
                                                                                                                                                                                                                                                                                                                                                                                                                # Basic sanitization - in production, use a more robust library
                                                                                                                                                                                                                                                                                                                                                                                                                        return text.replace("<", "&lt;").replace(">", "&gt;")